#remote_theme: pages-themes/merlot@v0.2.0
#remote_theme: pages-themes/minimal@v0.2.0    # allows going to home page
#remote_theme: pages-themes/slate@v0.2.0
#remote_theme: pages-themes/hacker@v0.2.0     # allows going to home page
remote_theme: pages-themes/cayman@v0.2.0
