title: Tech Leader Portfolio
description: "12+ years building high-performance teams and products"
email: contact@techleader.com
github_username: techleader
linkedin_username: techleader

# Theme settings
theme: minima
# Or choose another GitHub Pages supported theme:
# theme: jekyll-theme-minimal
# theme: jekyll-theme-cayman
# theme: jekyll-theme-slate

# If you want to use a remote theme (more options):
# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
# - jekyll-remote-theme

# Google Analytics
# google_analytics: UA-XXXXXXXX-X

# Show excerpts on the home page
show_excerpts: false

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git 